services:

    ########################################################################
    #   SPLASH CONSOLE COMMANDS
    ########################################################################
    
    Splash\Console\Command\:
        resource: '../../Command'
        calls:
            - [ setManager, [ "@event_dispatcher", "@logger", "%splash%" ]]
        tags:       
            - { name: "console.command"}        